fixtures:
  repositories:
    profiles: "https://github.com/esoptra/attachmentgenie-profiles.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "roles": "#{source_dir}"
